### ISSUE TITLE
[BUG] Running cell annotation when CELL_ANNOTATION_SOURCES are NULL

### ISSUE THREAD

**Issue by vucinick** [bioinfocz/scdrake#2]
## **Description**

I ran the default configuration on the example data (pbmc1k) in the Docker environment using the Docker image: `jirinovo/scdrake:1.5.0-bioc3.15`.

I made the following changes to the configuration files:

- **_02_norm_clustering.yaml_**
  - `CELL_ANNOTATION_SOURCES: null`

- **_pipeline.yaml_**
  - `DRAKE_TARGETS: ["report_input_qc", "report_norm_clustering", "report_norm_clustering_simple"]`

The pipeline failed at the `cell_annotation` target while executing `run_single_sample_r()`, resulting in the following error:

```R
✖ fail cell_annotation_c19514a9
Warning message:
ignoring targets not in the drake plan:
  config_integration
  config_int_clustering 
Error: 
! in callr subprocess.
Caused by error: 
! target cell_annotation_c19514a9 failed.
diagnose(cell_annotation_c19514a9)$error$message:
  Could not evaluate cli `{}` expression: `row$name`.
...
```

## **Expected behaviour**

The pipeline finishing without errors, and creating reports for quality control and normalization_clustering steps. Norm_clustering report should not contain cell annotation subchapter of the report

## **Current behaviour**

The pipeline fails when creating `cell_annotation` target. It should skip the cell annotation.

**Comment by gorgitko** [comment]
Fixed in https://github.com/bioinfocz/scdrake/pull/3
